### PR TITLE
Fix http://fineuploader.com/ invalid links

### PR DESCRIPTION
**Pull request by iwdmb**
Fix
+ deskpro logo

Add https
+ smartimage
+ dfstudio
+ storyboardthat
+ deskpro

### CODE REVIEW

**Comment by rnicholus** [comment]
Can you let me know where you obtained the new DeskPRO logo? Are you saying the logo on the DeskPRO site is incorrect? This is where we obtained the logo previously, as you can see in the markup. I'm not sure that the logo you provided will display appropriately on HiDPI displays. 

The HTTPS changes are fine, but unnecessary. FineUploader.com is not SSL, as it is a custom domain served over GitHub pages.

**Comment by iwdmb** [comment]
Hi, @rnicholus 

I get logo from the Deskpro website [https://www.deskpro.com/](https://www.deskpro.com/)

[http://fineuploader.com/](http://fineuploader.com/)

Deskpro logo link has failed. (Deskpro changed the logo link)

**Comment by rnicholus** [comment]
Looks like the new URL is https://www.deskpro.com/assets/build/img/deskpro/logo_2x.png. We should use that one instead as it seems to be tailored for HiDPI displays.

**Comment by rnicholus** [comment]
Thanks for reporting the logo issue. I just committed a fix.

**Pull request closed without merging**
